
services:
  bud-api-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bud-api-microservice
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    networks:
      - bud-api

  bud-api-postgres:
    image: postgres
    container_name: bud-api-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    volumes:
      - type: volume
        source: postgres_data
        target: ${POSTGRES_DATA:-/data/postgres}
    networks:
      - bud-api
    environment:
      - POSTGRES_USER=bud-api
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=budapi

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bud-api-celery
    env_file:
      - .env
    command: celery -A api worker --loglevel=info flower --port:5555
    networks:
      - bud-api

  flower:
    image: mher/flower
    container_name: bud-api-flower
    ports:
      - "5555:5555"
    command: ["flower", "--broker=amqp://guest@rabbitmq//"]
    networks:
      - bud-api

volumes:
  postgres_data:

networks:
  bud-api: