
services:
  bud-api-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bud-api-microservice
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    networks:
      - bud-api

  bud-api-postgres:
    image: postgres
    container_name: bud-api-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    volumes:
      - type: volume
        source: postgres_data
        target: ${POSTGRES_DATA:-/data/postgres}
    networks:
      - bud-api
    environment:
      - POSTGRES_USER=bud-api
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=budapi

volumes:
  postgres_data:

networks:
  bud-api: