# Generated by Django 5.1.5 on 2025-01-23 18:06

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('okr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('field', models.TextField()),
                ('old_state', models.TextField()),
                ('new_state', models.TextField()),
                ('author', models.TextField()),
            ],
            options={
                'db_table': 'task_history',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], default='Pending')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('support_team', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('key_result_id', models.ForeignKey(blank=True, db_column='key_result_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='okr.keyresult')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]