# Generated by Django 5.1.4 on 2025-01-08 20:23

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], default='Pending')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('initial_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.TextField()),
                ('support_team', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.board')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('field', models.TextField()),
                ('old_state', models.TextField()),
                ('new_state', models.TextField()),
                ('author', models.TextField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task')),
            ],
            options={
                'db_table': 'task_update',
            },
        ),
    ]
