# Generated by Django 5.1.5 on 2025-02-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
