# Generated by Django 5.1.5 on 2025-02-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0002_cycle_deleted_at_keyresult_deleted_at_and_more'),
        ('task_manager', '0002_task_deleted_at_alter_taskhistory_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'verbose_name_plural': 'Task Histories'},
        ),
        migrations.AddField(
            model_name='task',
            name='cycle',
            field=models.ForeignKey(blank=True, db_column='cycle_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='okr.cycle'),
        ),
        migrations.AddField(
            model_name='task',
            name='orderindex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='new_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='old_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
