# Generated by Django 5.1.5 on 2025-02-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_task_deleted_at_alter_taskhistory_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'verbose_name_plural': 'Task Histories'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('toDo', 'To Do'), ('doing', 'Doing'), ('done', 'Done')], default='pending'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='new_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='old_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
