# Generated by Django 5.1.5 on 2025-02-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_taskhistory_options_task_cycle_task_orderindex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='task_manager.task'),
        ),
    ]
