# Generated by Django 5.1.5 on 2025-02-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0002_cycle_deleted_at_keyresult_deleted_at_and_more'),
        ('task_manager', '0003_alter_taskhistory_options_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cycle',
            field=models.ForeignKey(blank=True, db_column='cycle_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='okr.cycle'),
        ),
        migrations.AddField(
            model_name='task',
            name='orderindex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='task_manager.task'),
        ),
    ]
