# Generated by Django 5.1.5 on 2025-02-03 21:02

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('period', models.CharField()),
                ('cadence', models.TextField(choices=[('YEARLY', 'Yearly'), ('QUARTERLY', 'Quarterly')])),
                ('active', models.BooleanField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='okr.cycle')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'db_table': 'cycle',
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('title', models.CharField()),
                ('goal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.TextField(choices=[('NUMBER', 'Number'), ('PERCENTAGE', 'Percentage'), ('COIN_BRL', 'Coin Brl'), ('COIN_USD', 'Coin Usd'), ('COIN_EUR', 'Coin Eur'), ('COIN_GBP', 'Coin Gbp')])),
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('ASCENDING', 'Ascending'), ('DESCENDING', 'Descending')])),
                ('mode', models.TextField(choices=[('COMPLETED', 'Completed'), ('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('DELETED', 'Deleted')])),
                ('comment_count', models.JSONField()),
                ('last_updated_by', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'db_table': 'key_result',
            },
        ),
        migrations.CreateModel(
            name='KeyResultCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('confidence', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okr.keyresult')),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='okr.keyresultcheckin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'key_result_check_in',
            },
        ),
        migrations.CreateModel(
            name='KeyResultCheckMark',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('state', models.TextField(choices=[('CHECKED', 'Checked'), ('UNCHECKED', 'Unchecked')])),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user_set', to=settings.AUTH_USER_MODEL)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okr.keyresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'key_result_check_mark',
            },
        ),
        migrations.CreateModel(
            name='KeyResultComment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.TextField(choices=[('suggestion', 'Suggestion'), ('praisal', 'Praisal'), ('question', 'Question'), ('alignment', 'Alignment'), ('improvement', 'Improvement'), ('issue', 'Issue'), ('comment', 'Comment')])),
                ('extra', models.TextField(blank=True, null=True)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okr.keyresult')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='okr.keyresultcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'key_result_comment',
            },
        ),
        migrations.CreateModel(
            name='KeyResultSupportTeamMembersUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='okr.keyresult')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'key_result_support_team_members_user',
            },
        ),
        migrations.AddField(
            model_name='keyresult',
            name='support_team',
            field=models.ManyToManyField(related_name='suport_team_key_result', through='okr.KeyResultSupportTeamMembersUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KeyResultUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.JSONField()),
                ('old_state', models.JSONField()),
                ('patches', models.JSONField()),
                ('new_state', models.JSONField()),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='okr.keyresult')),
            ],
            options={
                'db_table': 'key_result_update',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('title', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, null=True)),
                ('mode', models.TextField(choices=[('COMPLETED', 'Completed'), ('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('DELETED', 'Deleted')])),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okr.cycle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'db_table': 'objective',
            },
        ),
        migrations.AddField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okr.objective'),
        ),
    ]

