# Generated by Django 5.1.5 on 2025-02-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyresultcheckin',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyresultcheckin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='keyresultcheckmark',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyresultcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyresultupdate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyresultupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
