# Generated by Django 5.1.5 on 2025-01-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('okr', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='team.team'
            ),
        ),
    ]
