# Generated by Django 5.1.5 on 2025-02-03 21:02

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('authz_sub', models.CharField()),
                ('role', models.CharField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, null=True)),
                ('linked_in_profile_address', models.CharField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('email', models.TextField(db_collation='und-x-icu', unique=True)),
                ('status', models.TextField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('key', models.TextField(choices=[('LOCALE', 'Locale')])),
                ('value', models.CharField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('preferences', models.JSONField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_setting',
            },
        ),
    ]
