# Generated by Django 5.1.5 on 2025-02-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
