name: test

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  deploy:
    uses: budproj/github-actions/.github/workflows/ci.yaml@feat/ci
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
